import type { LocaleId } from '../../shared/ui/locale.js';

const PT = {
  tituloLista: 'Anotações',
  novaNota: 'Nova anotação',
  editar: 'Editar',
  apagar: 'Apagar',
  salvar: 'Salvar',
  voltarLista: 'Voltar à lista',
  modoApresentacao: 'Modo apresentação',
  modoEdicao: 'Modo edição',
  ecranInteiro: 'Ecrã inteiro',
  sairEcranInteiro: 'Sair do ecrã inteiro',
  autoScroll: 'Auto-rolagem',
  pausarAutoScroll: 'Pausar rolagem',
  proximoFoco: 'Próximo foco',
  tituloPlaceholder: 'Título',
  pastaLabel: 'Pasta',
  pastaTodas: 'Todas',
  pastaNenhuma: 'Sem pasta',
  buscarTitulo: 'Buscar no título',
  buscarEtiquetas: 'Etiquetas (contém)',
  filtroTipoModelo: 'Modelo',
  modeloTodos: 'Todos',
  somenteAtivas: 'Ocultar arquivadas',
  listaVazia: 'Nenhuma anotação. Crie uma nota nova.',
  inserirImagem: 'Inserir imagem (WebP/SVG)',
  confirmarApagarTitulo: 'Apagar esta anotação?',
  confirmarApagarDescricao:
    'O conteúdo será eliminado da base local. Esta operação não tem volta.',
  erroCarregar: 'Não foi possível carregar a nota.',
  erroIdInvalido: 'Identificador inválido.',
  notaSemTituloFallback: '(sem título)',
  arquivada: 'Arquivada',
  fixada: 'Fixada',
  modeloNotaLabel: 'Modelo / template',
  aplicarEsqueleto: 'Aplicar estrutura do modelo…',
  confirmarSubstituirCorpoTitulo: 'Substituir todo o texto pelo modelo?',
  confirmarSubstituirCorpoDescricao:
    'O conteúdo atual do editor será substituído. Podes cancelar ou guardar antes se precisares.',
  etiquetasLabel: 'Etiquetas',
  etiquetasAjuda: 'Separadas por vírgula.',
  formatoToolbarAria: 'Formatar texto',
  toolbarNegrito: 'Negrito',
  toolbarItalico: 'Itálico',
  toolbarSubtitulo: 'Subtítulo',
  toolbarListaMarcadores: 'Lista com marcadores',
  toolbarListaNumerada: 'Lista numerada',
  toolbarDesfazer: 'Desfazer',
  toolbarRefazer: 'Refazer',
  cancelarDialogo: 'Cancelar',
  erroLista: 'Erro ao carregar lista.',
  metaModelo: 'Modelo',
  metaEtiquetas: 'Etiquetas',
} as const;

const EN = {
  tituloLista: 'Notes',
  novaNota: 'New note',
  editar: 'Edit',
  apagar: 'Delete',
  salvar: 'Save',
  voltarLista: 'Back to list',
  modoApresentacao: 'Presentation',
  modoEdicao: 'Edit mode',
  ecranInteiro: 'Fullscreen',
  sairEcranInteiro: 'Exit fullscreen',
  autoScroll: 'Auto-scroll',
  pausarAutoScroll: 'Pause scroll',
  proximoFoco: 'Next focus',
  tituloPlaceholder: 'Title',
  pastaLabel: 'Folder',
  pastaTodas: 'All',
  pastaNenhuma: 'No folder',
  buscarTitulo: 'Search in title',
  buscarEtiquetas: 'Tags (contains)',
  filtroTipoModelo: 'Template',
  modeloTodos: 'All',
  somenteAtivas: 'Hide archived',
  listaVazia: 'No notes yet. Create a new note.',
  inserirImagem: 'Insert image (WebP/SVG)',
  confirmarApagarTitulo: 'Delete this note?',
  confirmarApagarDescricao:
    'Content will be removed from the local database. This cannot be undone.',
  erroCarregar: 'Could not load the note.',
  erroIdInvalido: 'Invalid identifier.',
  notaSemTituloFallback: '(untitled)',
  arquivada: 'Archived',
  fixada: 'Pinned',
  modeloNotaLabel: 'Template',
  aplicarEsqueleto: 'Apply template outline…',
  confirmarSubstituirCorpoTitulo: 'Replace all text with this template?',
  confirmarSubstituirCorpoDescricao:
    'The current editor content will be replaced. Cancel or save first if needed.',
  etiquetasLabel: 'Tags',
  etiquetasAjuda: 'Comma-separated.',
  formatoToolbarAria: 'Format text',
  toolbarNegrito: 'Bold',
  toolbarItalico: 'Italic',
  toolbarSubtitulo: 'Subtitle',
  toolbarListaMarcadores: 'Bulleted list',
  toolbarListaNumerada: 'Numbered list',
  toolbarDesfazer: 'Undo',
  toolbarRefazer: 'Redo',
  cancelarDialogo: 'Cancel',
  erroLista: 'Could not load the list.',
  metaModelo: 'Template',
  metaEtiquetas: 'Tags',
} as const;

export type TextosAnotacao = typeof PT;

export function obterTextosAnotacao(locale: LocaleId): TextosAnotacao {
  return (locale === 'en' ? EN : PT) as TextosAnotacao;
}
